# Generated by Django 5.2.13 on 2026-04-28 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_num', models.IntegerField(verbose_name='Phase 번호')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Phase명')),
                ('goal', models.TextField(blank=True, verbose_name='목표')),
                ('status', models.CharField(choices=[('done', '완료'), ('in_progress', '진행 중'), ('pending', '대기')], default='pending', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('done_items', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phase',
                'db_table': 'phase',
                'ordering': ['phase_num'],
                'unique_together': {('project', 'phase_num')},
            },
        ),
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='앱명')),
                ('responsibility', models.TextField(blank=True, verbose_name='책임')),
                ('model_count', models.IntegerField(default=0)),
                ('service_count', models.IntegerField(default=0)),
                ('raw_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_modules', to='projects.project')),
            ],
            options={
                'verbose_name': '앱 모듈',
                'verbose_name_plural': '앱 모듈',
                'db_table': 'app_module',
                'unique_together': {('project', 'app_name')},
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(blank=True, max_length=50, verbose_name='연결 SCR')),
                ('feature_id', models.CharField(max_length=50, verbose_name='기능 ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='기능명')),
                ('status', models.CharField(choices=[('implemented', '구현 완료'), ('not_implemented', '미구현'), ('unknown', '미상')], default='unknown', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=4)),
                ('raw_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.project')),
            ],
            options={
                'verbose_name': '기능',
                'verbose_name_plural': '기능',
                'db_table': 'feature',
                'indexes': [models.Index(fields=['project', 'status'], name='idx_feature_status')],
                'unique_together': {('project', 'feature_id')},
            },
        ),
        migrations.CreateModel(
            name='FeatureMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(blank=True, max_length=50)),
                ('feature_name', models.CharField(blank=True, max_length=300)),
                ('entry_point', models.CharField(blank=True, max_length=500, verbose_name='진입점')),
                ('view_handler', models.CharField(blank=True, max_length=500, verbose_name='뷰 핸들러')),
                ('service', models.CharField(blank=True, max_length=500)),
                ('model_db', models.CharField(blank=True, max_length=500, verbose_name='모델/DB')),
                ('template_ui', models.CharField(blank=True, max_length=500)),
                ('external_api', models.CharField(blank=True, max_length=500, verbose_name='외부 API')),
                ('raw_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_maps', to='projects.project')),
            ],
            options={
                'verbose_name': '기능 매핑',
                'verbose_name_plural': '기능 매핑',
                'db_table': 'feature_map',
                'indexes': [models.Index(fields=['project'], name='idx_featuremap_project')],
            },
        ),
        migrations.CreateModel(
            name='ImprovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=4)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True)),
                ('phase_target', models.CharField(blank=True, max_length=50, verbose_name='구현 예정 Phase')),
                ('is_done', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_items', to='projects.project')),
            ],
            options={
                'verbose_name': '개선 항목',
                'verbose_name_plural': '개선 항목',
                'db_table': 'improvement_item',
                'indexes': [models.Index(fields=['project', 'priority', 'is_done'], name='idx_improvement_priority')],
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('fields', models.TextField(blank=True, verbose_name='필드 JSON')),
                ('raw_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_infos', to='projects.project')),
            ],
            options={
                'verbose_name': '모델 정보',
                'verbose_name_plural': '모델 정보',
                'db_table': 'model_info',
                'unique_together': {('project', 'app_name', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=4)),
                ('content', models.TextField(verbose_name='내용')),
                ('is_done', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='projects.project')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='dashboard.phase')),
            ],
            options={
                'verbose_name': '체크리스트 항목',
                'verbose_name_plural': '체크리스트 항목',
                'db_table': 'checklist_item',
                'indexes': [models.Index(fields=['phase', 'is_done'], name='idx_checklist_phase')],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(max_length=50, verbose_name='화면 ID')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='카테고리')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='화면명')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='URL')),
                ('raw_text', models.TextField(blank=True, verbose_name='원문')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='projects.project')),
            ],
            options={
                'verbose_name': '화면',
                'verbose_name_plural': '화면',
                'db_table': 'screen',
                'unique_together': {('project', 'screen_id')},
            },
        ),
    ]
