# Generated by Django 5.2.13 on 2026-04-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True, verbose_name='절대 경로')),
                ('name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
                'db_table': 'project',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='idx_project_active')],
            },
        ),
    ]
