# Generated by Django 5.2.13 on 2026-04-28 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='파일명')),
                ('file_mtime', models.DateTimeField(blank=True, null=True, verbose_name='파일 mtime')),
                ('changed', models.BooleanField(default=False, verbose_name='변경 여부')),
                ('result', models.CharField(blank=True, choices=[('success', '성공'), ('failed', '실패'), ('no_change', '변경 없음')], max_length=20)),
                ('detail', models.TextField(blank=True, verbose_name='요약/오류')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='동기화 시각')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='projects.project')),
            ],
            options={
                'verbose_name': '동기화 로그',
                'verbose_name_plural': '동기화 로그',
                'db_table': 'sync_log',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['project', '-synced_at'], name='idx_synclog_project_time')],
            },
        ),
    ]
